/*
Copyright The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	v1beta1 "github.com/onosproject/onos-operator/pkg/apis/topo/v1beta1"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	labels "k8s.io/apimachinery/pkg/labels"
	schema "k8s.io/apimachinery/pkg/runtime/schema"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	testing "k8s.io/client-go/testing"
)

// FakeKinds implements KindInterface
type FakeKinds struct {
	Fake *FakeTopoV1beta1
	ns   string
}

var kindsResource = schema.GroupVersionResource{Group: "topo.onosproject.org", Version: "v1beta1", Resource: "kinds"}

var kindsKind = schema.GroupVersionKind{Group: "topo.onosproject.org", Version: "v1beta1", Kind: "Kind"}

// Get takes name of the kind, and returns the corresponding kind object, and an error if there is any.
func (c *FakeKinds) Get(name string, options v1.GetOptions) (result *v1beta1.Kind, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewGetAction(kindsResource, c.ns, name), &v1beta1.Kind{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1beta1.Kind), err
}

// List takes label and field selectors, and returns the list of Kinds that match those selectors.
func (c *FakeKinds) List(opts v1.ListOptions) (result *v1beta1.KindList, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewListAction(kindsResource, kindsKind, c.ns, opts), &v1beta1.KindList{})

	if obj == nil {
		return nil, err
	}

	label, _, _ := testing.ExtractFromListOptions(opts)
	if label == nil {
		label = labels.Everything()
	}
	list := &v1beta1.KindList{ListMeta: obj.(*v1beta1.KindList).ListMeta}
	for _, item := range obj.(*v1beta1.KindList).Items {
		if label.Matches(labels.Set(item.Labels)) {
			list.Items = append(list.Items, item)
		}
	}
	return list, err
}

// Watch returns a watch.Interface that watches the requested kinds.
func (c *FakeKinds) Watch(opts v1.ListOptions) (watch.Interface, error) {
	return c.Fake.
		InvokesWatch(testing.NewWatchAction(kindsResource, c.ns, opts))

}

// Create takes the representation of a kind and creates it.  Returns the server's representation of the kind, and an error, if there is any.
func (c *FakeKinds) Create(kind *v1beta1.Kind) (result *v1beta1.Kind, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewCreateAction(kindsResource, c.ns, kind), &v1beta1.Kind{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1beta1.Kind), err
}

// Update takes the representation of a kind and updates it. Returns the server's representation of the kind, and an error, if there is any.
func (c *FakeKinds) Update(kind *v1beta1.Kind) (result *v1beta1.Kind, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateAction(kindsResource, c.ns, kind), &v1beta1.Kind{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1beta1.Kind), err
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
func (c *FakeKinds) UpdateStatus(kind *v1beta1.Kind) (*v1beta1.Kind, error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateSubresourceAction(kindsResource, "status", c.ns, kind), &v1beta1.Kind{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1beta1.Kind), err
}

// Delete takes name of the kind and deletes it. Returns an error if one occurs.
func (c *FakeKinds) Delete(name string, options *v1.DeleteOptions) error {
	_, err := c.Fake.
		Invokes(testing.NewDeleteAction(kindsResource, c.ns, name), &v1beta1.Kind{})

	return err
}

// DeleteCollection deletes a collection of objects.
func (c *FakeKinds) DeleteCollection(options *v1.DeleteOptions, listOptions v1.ListOptions) error {
	action := testing.NewDeleteCollectionAction(kindsResource, c.ns, listOptions)

	_, err := c.Fake.Invokes(action, &v1beta1.KindList{})
	return err
}

// Patch applies the patch and returns the patched kind.
func (c *FakeKinds) Patch(name string, pt types.PatchType, data []byte, subresources ...string) (result *v1beta1.Kind, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewPatchSubresourceAction(kindsResource, c.ns, name, pt, data, subresources...), &v1beta1.Kind{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1beta1.Kind), err
}
