/*
Copyright The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	v1beta1 "github.com/onosproject/onos-operator/pkg/apis/topo/v1beta1"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	labels "k8s.io/apimachinery/pkg/labels"
	schema "k8s.io/apimachinery/pkg/runtime/schema"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	testing "k8s.io/client-go/testing"
)

// FakeRelations implements RelationInterface
type FakeRelations struct {
	Fake *FakeTopoV1beta1
	ns   string
}

var relationsResource = schema.GroupVersionResource{Group: "topo.onosproject.org", Version: "v1beta1", Resource: "relations"}

var relationsKind = schema.GroupVersionKind{Group: "topo.onosproject.org", Version: "v1beta1", Kind: "Relation"}

// Get takes name of the relation, and returns the corresponding relation object, and an error if there is any.
func (c *FakeRelations) Get(name string, options v1.GetOptions) (result *v1beta1.Relation, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewGetAction(relationsResource, c.ns, name), &v1beta1.Relation{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1beta1.Relation), err
}

// List takes label and field selectors, and returns the list of Relations that match those selectors.
func (c *FakeRelations) List(opts v1.ListOptions) (result *v1beta1.RelationList, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewListAction(relationsResource, relationsKind, c.ns, opts), &v1beta1.RelationList{})

	if obj == nil {
		return nil, err
	}

	label, _, _ := testing.ExtractFromListOptions(opts)
	if label == nil {
		label = labels.Everything()
	}
	list := &v1beta1.RelationList{ListMeta: obj.(*v1beta1.RelationList).ListMeta}
	for _, item := range obj.(*v1beta1.RelationList).Items {
		if label.Matches(labels.Set(item.Labels)) {
			list.Items = append(list.Items, item)
		}
	}
	return list, err
}

// Watch returns a watch.Interface that watches the requested relations.
func (c *FakeRelations) Watch(opts v1.ListOptions) (watch.Interface, error) {
	return c.Fake.
		InvokesWatch(testing.NewWatchAction(relationsResource, c.ns, opts))

}

// Create takes the representation of a relation and creates it.  Returns the server's representation of the relation, and an error, if there is any.
func (c *FakeRelations) Create(relation *v1beta1.Relation) (result *v1beta1.Relation, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewCreateAction(relationsResource, c.ns, relation), &v1beta1.Relation{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1beta1.Relation), err
}

// Update takes the representation of a relation and updates it. Returns the server's representation of the relation, and an error, if there is any.
func (c *FakeRelations) Update(relation *v1beta1.Relation) (result *v1beta1.Relation, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateAction(relationsResource, c.ns, relation), &v1beta1.Relation{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1beta1.Relation), err
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
func (c *FakeRelations) UpdateStatus(relation *v1beta1.Relation) (*v1beta1.Relation, error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateSubresourceAction(relationsResource, "status", c.ns, relation), &v1beta1.Relation{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1beta1.Relation), err
}

// Delete takes name of the relation and deletes it. Returns an error if one occurs.
func (c *FakeRelations) Delete(name string, options *v1.DeleteOptions) error {
	_, err := c.Fake.
		Invokes(testing.NewDeleteAction(relationsResource, c.ns, name), &v1beta1.Relation{})

	return err
}

// DeleteCollection deletes a collection of objects.
func (c *FakeRelations) DeleteCollection(options *v1.DeleteOptions, listOptions v1.ListOptions) error {
	action := testing.NewDeleteCollectionAction(relationsResource, c.ns, listOptions)

	_, err := c.Fake.Invokes(action, &v1beta1.RelationList{})
	return err
}

// Patch applies the patch and returns the patched relation.
func (c *FakeRelations) Patch(name string, pt types.PatchType, data []byte, subresources ...string) (result *v1beta1.Relation, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewPatchSubresourceAction(relationsResource, c.ns, name, pt, data, subresources...), &v1beta1.Relation{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1beta1.Relation), err
}
