/*
Copyright The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	v1beta1 "github.com/onosproject/onos-operator/pkg/apis/core/v1beta1"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	labels "k8s.io/apimachinery/pkg/labels"
	schema "k8s.io/apimachinery/pkg/runtime/schema"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	testing "k8s.io/client-go/testing"
)

// FakeMicroservices implements MicroserviceInterface
type FakeMicroservices struct {
	Fake *FakeCoreV1beta1
	ns   string
}

var microservicesResource = schema.GroupVersionResource{Group: "core.onosproject.org", Version: "v1beta1", Resource: "microservices"}

var microservicesKind = schema.GroupVersionKind{Group: "core.onosproject.org", Version: "v1beta1", Kind: "Microservice"}

// Get takes name of the microservice, and returns the corresponding microservice object, and an error if there is any.
func (c *FakeMicroservices) Get(name string, options v1.GetOptions) (result *v1beta1.Microservice, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewGetAction(microservicesResource, c.ns, name), &v1beta1.Microservice{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1beta1.Microservice), err
}

// List takes label and field selectors, and returns the list of Microservices that match those selectors.
func (c *FakeMicroservices) List(opts v1.ListOptions) (result *v1beta1.MicroserviceList, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewListAction(microservicesResource, microservicesKind, c.ns, opts), &v1beta1.MicroserviceList{})

	if obj == nil {
		return nil, err
	}

	label, _, _ := testing.ExtractFromListOptions(opts)
	if label == nil {
		label = labels.Everything()
	}
	list := &v1beta1.MicroserviceList{ListMeta: obj.(*v1beta1.MicroserviceList).ListMeta}
	for _, item := range obj.(*v1beta1.MicroserviceList).Items {
		if label.Matches(labels.Set(item.Labels)) {
			list.Items = append(list.Items, item)
		}
	}
	return list, err
}

// Watch returns a watch.Interface that watches the requested microservices.
func (c *FakeMicroservices) Watch(opts v1.ListOptions) (watch.Interface, error) {
	return c.Fake.
		InvokesWatch(testing.NewWatchAction(microservicesResource, c.ns, opts))

}

// Create takes the representation of a microservice and creates it.  Returns the server's representation of the microservice, and an error, if there is any.
func (c *FakeMicroservices) Create(microservice *v1beta1.Microservice) (result *v1beta1.Microservice, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewCreateAction(microservicesResource, c.ns, microservice), &v1beta1.Microservice{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1beta1.Microservice), err
}

// Update takes the representation of a microservice and updates it. Returns the server's representation of the microservice, and an error, if there is any.
func (c *FakeMicroservices) Update(microservice *v1beta1.Microservice) (result *v1beta1.Microservice, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateAction(microservicesResource, c.ns, microservice), &v1beta1.Microservice{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1beta1.Microservice), err
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
func (c *FakeMicroservices) UpdateStatus(microservice *v1beta1.Microservice) (*v1beta1.Microservice, error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateSubresourceAction(microservicesResource, "status", c.ns, microservice), &v1beta1.Microservice{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1beta1.Microservice), err
}

// Delete takes name of the microservice and deletes it. Returns an error if one occurs.
func (c *FakeMicroservices) Delete(name string, options *v1.DeleteOptions) error {
	_, err := c.Fake.
		Invokes(testing.NewDeleteAction(microservicesResource, c.ns, name), &v1beta1.Microservice{})

	return err
}

// DeleteCollection deletes a collection of objects.
func (c *FakeMicroservices) DeleteCollection(options *v1.DeleteOptions, listOptions v1.ListOptions) error {
	action := testing.NewDeleteCollectionAction(microservicesResource, c.ns, listOptions)

	_, err := c.Fake.Invokes(action, &v1beta1.MicroserviceList{})
	return err
}

// Patch applies the patch and returns the patched microservice.
func (c *FakeMicroservices) Patch(name string, pt types.PatchType, data []byte, subresources ...string) (result *v1beta1.Microservice, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewPatchSubresourceAction(microservicesResource, c.ns, name, pt, data, subresources...), &v1beta1.Microservice{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1beta1.Microservice), err
}
