apiVersion: topo.onosproject.org/v1beta1
kind: Entity
metadata:
  name:  network-layer.0.underlay-1
spec:
  uri: network-layer:0/underlay-1 # network-layer:type/name
  kind:
    name: network-layer
  aspects:
    onos.topo.NetworkLayer:
      type: "UNDERLAY"
      display_name: "Underlay-1"
---
apiVersion: topo.onosproject.org/v1beta1
kind: Entity
metadata:
  name: p4rt.1
spec:
  uri: p4rt:1 # protocol:switch_id
  kind:
    name: switch
  aspects:
    onos.topo.Switch:
      model_id: "test"
      role: "leaf"
    onos.topo.P4RTServerInfo:
      control_endpoint:
        address: stratum-simulator
        port: 50002
    onos.topo.TLSOptions:
      plain: true
      insecure: true
---
apiVersion: topo.onosproject.org/v1beta1
kind: Entity
metadata:
  name: p4rt.1.1.0
spec:
  uri: p4rt:1/1/0 # protocol:switchID/port_number/channel_number
  kind:
    name: port
  aspects:
    onos.topo.PhyPort:
      port_number: 1
      display_name: "p4rt:1/1/0"
      speed: "40G"
      channel_number: 0
---
apiVersion: topo.onosproject.org/v1beta1
kind: Entity
metadata:
  name: p4rt.2.1.0
spec:
  uri: p4rt:2/1/0 # protocol:switchID/port_number/channel_number
  kind:
    name: port
  aspects:
    onos.topo.PhyPort:
      port_number: 1
      display_name: "p4rt:1/1/0"
      speed: "40G"
      channel_number: 0

---
apiVersion: topo.onosproject.org/v1beta1
kind: Entity
metadata:
  name: p4rt.1.1.0-p4rt.2.1.0  # source port uri-destination port uri
spec:
  uri: p4rt:1/1/0-p4rt:2/1/0
  kind:
    name: link
  aspects:

---
apiVersion: topo.onosproject.org/v1beta1
kind: Relation
metadata:
  name: uuid.123 # we can assign uuid for each originates relation
spec:
  uri: uuid:123
  kind:
    name: originates
  source:
    uri:  p4rt:1/1/0
    name: p4rt.1.1.0
  target:
    uri:  p4rt:1/1/0-p4rt:2/1/0
    name: p4rt.1.1.0-p4rt.2.1.0
---
apiVersion: topo.onosproject.org/v1beta1
kind: Relation
metadata:
  name: uuid.124 # we can assign uuid for each terminates relation
spec:
  uri: uuid:124
  kind:
    name: terminates
  source:
    uri:  p4rt:2/1/0
    name: p4rt.2.1.0
  target:
    uri:  p4rt:1/1/0-p4rt:2/1/0
    name: p4rt.1.1.0-p4rt.2.1.0