/*
Copyright The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	v1beta1 "github.com/onosproject/onos-operator/pkg/apis/config/v1beta1"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	labels "k8s.io/apimachinery/pkg/labels"
	schema "k8s.io/apimachinery/pkg/runtime/schema"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	testing "k8s.io/client-go/testing"
)

// FakeModels implements ModelInterface
type FakeModels struct {
	Fake *FakeConfigV1beta1
	ns   string
}

var modelsResource = schema.GroupVersionResource{Group: "config.onosproject.org", Version: "v1beta1", Resource: "models"}

var modelsKind = schema.GroupVersionKind{Group: "config.onosproject.org", Version: "v1beta1", Kind: "Model"}

// Get takes name of the model, and returns the corresponding model object, and an error if there is any.
func (c *FakeModels) Get(name string, options v1.GetOptions) (result *v1beta1.Model, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewGetAction(modelsResource, c.ns, name), &v1beta1.Model{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1beta1.Model), err
}

// List takes label and field selectors, and returns the list of Models that match those selectors.
func (c *FakeModels) List(opts v1.ListOptions) (result *v1beta1.ModelList, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewListAction(modelsResource, modelsKind, c.ns, opts), &v1beta1.ModelList{})

	if obj == nil {
		return nil, err
	}

	label, _, _ := testing.ExtractFromListOptions(opts)
	if label == nil {
		label = labels.Everything()
	}
	list := &v1beta1.ModelList{ListMeta: obj.(*v1beta1.ModelList).ListMeta}
	for _, item := range obj.(*v1beta1.ModelList).Items {
		if label.Matches(labels.Set(item.Labels)) {
			list.Items = append(list.Items, item)
		}
	}
	return list, err
}

// Watch returns a watch.Interface that watches the requested models.
func (c *FakeModels) Watch(opts v1.ListOptions) (watch.Interface, error) {
	return c.Fake.
		InvokesWatch(testing.NewWatchAction(modelsResource, c.ns, opts))

}

// Create takes the representation of a model and creates it.  Returns the server's representation of the model, and an error, if there is any.
func (c *FakeModels) Create(model *v1beta1.Model) (result *v1beta1.Model, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewCreateAction(modelsResource, c.ns, model), &v1beta1.Model{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1beta1.Model), err
}

// Update takes the representation of a model and updates it. Returns the server's representation of the model, and an error, if there is any.
func (c *FakeModels) Update(model *v1beta1.Model) (result *v1beta1.Model, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateAction(modelsResource, c.ns, model), &v1beta1.Model{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1beta1.Model), err
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
func (c *FakeModels) UpdateStatus(model *v1beta1.Model) (*v1beta1.Model, error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateSubresourceAction(modelsResource, "status", c.ns, model), &v1beta1.Model{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1beta1.Model), err
}

// Delete takes name of the model and deletes it. Returns an error if one occurs.
func (c *FakeModels) Delete(name string, options *v1.DeleteOptions) error {
	_, err := c.Fake.
		Invokes(testing.NewDeleteAction(modelsResource, c.ns, name), &v1beta1.Model{})

	return err
}

// DeleteCollection deletes a collection of objects.
func (c *FakeModels) DeleteCollection(options *v1.DeleteOptions, listOptions v1.ListOptions) error {
	action := testing.NewDeleteCollectionAction(modelsResource, c.ns, listOptions)

	_, err := c.Fake.Invokes(action, &v1beta1.ModelList{})
	return err
}

// Patch applies the patch and returns the patched model.
func (c *FakeModels) Patch(name string, pt types.PatchType, data []byte, subresources ...string) (result *v1beta1.Model, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewPatchSubresourceAction(modelsResource, c.ns, name, pt, data, subresources...), &v1beta1.Model{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1beta1.Model), err
}
