/*
Copyright The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package v1beta1

import (
	"context"
	"time"

	scheme "github.com/onosproject/onos-operator/pkg/clientset/versioned/scheme"
	v1beta1 "github.com/onosproject/onos-operator/pkg/apis/config/v1beta1"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	rest "k8s.io/client-go/rest"
)

// ModelRegistriesGetter has a method to return a ModelRegistryInterface.
// A group's client should implement this interface.
type ModelRegistriesGetter interface {
	ModelRegistries(namespace string) ModelRegistryInterface
}

// ModelRegistryInterface has methods to work with ModelRegistry resources.
type ModelRegistryInterface interface {
	Create(*v1beta1.ModelRegistry) (*v1beta1.ModelRegistry, error)
	Update(*v1beta1.ModelRegistry) (*v1beta1.ModelRegistry, error)
	Delete(name string, options *v1.DeleteOptions) error
	DeleteCollection(options *v1.DeleteOptions, listOptions v1.ListOptions) error
	Get(name string, options v1.GetOptions) (*v1beta1.ModelRegistry, error)
	List(opts v1.ListOptions) (*v1beta1.ModelRegistryList, error)
	Watch(opts v1.ListOptions) (watch.Interface, error)
	Patch(name string, pt types.PatchType, data []byte, subresources ...string) (result *v1beta1.ModelRegistry, err error)
	ModelRegistryExpansion
}

// modelRegistries implements ModelRegistryInterface
type modelRegistries struct {
	client rest.Interface
	ns     string
}

// newModelRegistries returns a ModelRegistries
func newModelRegistries(c *ConfigV1beta1Client, namespace string) *modelRegistries {
	return &modelRegistries{
		client: c.RESTClient(),
		ns:     namespace,
	}
}

// Get takes name of the modelRegistry, and returns the corresponding modelRegistry object, and an error if there is any.
func (c *modelRegistries) Get(name string, options v1.GetOptions) (result *v1beta1.ModelRegistry, err error) {
	result = &v1beta1.ModelRegistry{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("modelregistries").
		Name(name).
		VersionedParams(&options, scheme.ParameterCodec).
		Do(context.TODO()).
		Into(result)
	return
}

// List takes label and field selectors, and returns the list of ModelRegistries that match those selectors.
func (c *modelRegistries) List(opts v1.ListOptions) (result *v1beta1.ModelRegistryList, err error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	result = &v1beta1.ModelRegistryList{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("modelregistries").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Do(context.TODO()).
		Into(result)
	return
}

// Watch returns a watch.Interface that watches the requested modelRegistries.
func (c *modelRegistries) Watch(opts v1.ListOptions) (watch.Interface, error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	opts.Watch = true
	return c.client.Get().
		Namespace(c.ns).
		Resource("modelregistries").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Watch(context.TODO())
}

// Create takes the representation of a modelRegistry and creates it.  Returns the server's representation of the modelRegistry, and an error, if there is any.
func (c *modelRegistries) Create(modelRegistry *v1beta1.ModelRegistry) (result *v1beta1.ModelRegistry, err error) {
	result = &v1beta1.ModelRegistry{}
	err = c.client.Post().
		Namespace(c.ns).
		Resource("modelregistries").
		Body(modelRegistry).
		Do(context.TODO()).
		Into(result)
	return
}

// Update takes the representation of a modelRegistry and updates it. Returns the server's representation of the modelRegistry, and an error, if there is any.
func (c *modelRegistries) Update(modelRegistry *v1beta1.ModelRegistry) (result *v1beta1.ModelRegistry, err error) {
	result = &v1beta1.ModelRegistry{}
	err = c.client.Put().
		Namespace(c.ns).
		Resource("modelregistries").
		Name(modelRegistry.Name).
		Body(modelRegistry).
		Do(context.TODO()).
		Into(result)
	return
}

// Delete takes name of the modelRegistry and deletes it. Returns an error if one occurs.
func (c *modelRegistries) Delete(name string, options *v1.DeleteOptions) error {
	return c.client.Delete().
		Namespace(c.ns).
		Resource("modelregistries").
		Name(name).
		Body(options).
		Do(context.TODO()).
		Error()
}

// DeleteCollection deletes a collection of objects.
func (c *modelRegistries) DeleteCollection(options *v1.DeleteOptions, listOptions v1.ListOptions) error {
	var timeout time.Duration
	if listOptions.TimeoutSeconds != nil {
		timeout = time.Duration(*listOptions.TimeoutSeconds) * time.Second
	}
	return c.client.Delete().
		Namespace(c.ns).
		Resource("modelregistries").
		VersionedParams(&listOptions, scheme.ParameterCodec).
		Timeout(timeout).
		Body(options).
		Do(context.TODO()).
		Error()
}

// Patch applies the patch and returns the patched modelRegistry.
func (c *modelRegistries) Patch(name string, pt types.PatchType, data []byte, subresources ...string) (result *v1beta1.ModelRegistry, err error) {
	result = &v1beta1.ModelRegistry{}
	err = c.client.Patch(pt).
		Namespace(c.ns).
		Resource("modelregistries").
		SubResource(subresources...).
		Name(name).
		Body(data).
		Do(context.TODO()).
		Into(result)
	return
}
